### ISSUE TITLE
Export more than 65536 rows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jnash67/tableexport-for-vaadin#27]
```
What steps will reproduce the problem?
1. Trying to export more than 655366 rows will throw an exception.

It'll be helpful if at least I can Split the table in parts, so It'll be 
exported in multiple files, I'm working with 230000+ rows...

```

Original issue reported on code.google.com by `jgama...@jarris.com.co` on 3 Aug 2012 at 4:20

**Comment by jnash67** [comment]
Incorporated alternate solution contributed by Marco Petris:

---

We created a CvsExport based on JavaCsv (http://sourceforge.net/projects/javacsv/) that extends TableExport. So you get the same API but without the xls limit. It can be found at https://github.com/mpetris/catma/blob/master/src/de/catma/ui/component/export/CsvExport.java. It's published under gpl v3.
