### ISSUE TITLE
Cannot find jar on Maven

### ISSUE THREAD

**Issue by victoraduarte** [jnash67/tableexport-for-vaadin#54]
Have tried everything to find this jar on Maven with no luck. Have other Vaadin add-ons (eg, stepper, messagebox, etc) with no problem. Have had to resort to downloading the jar locally but would prefer a working maven dependency section and repository link. Functionality seems to be really nice.

**Comment by mletenay** [comment]
You have probably wrong <groupId> in pom.xml.
Most of other plugins use _org.vaadin.addons_ but this one is _com.vaadin.addon_
